# Generated by Django 6.0.2 on 2026-02-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('cloud', 'Cloud Computing'), ('ai_ml', 'AI / Machine Learning'), ('web', 'Web Development'), ('cyber', 'Cybersecurity'), ('data', 'Data Science & Analytics'), ('devops', 'DevOps & CI/CD'), ('mobile', 'Mobile Development'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='skill_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated skill tags, e.g. Python, AWS, Docker', max_length=300),
        ),
    ]
